Repository Terasology/Inventory, pull requests merged in 2021-08, with the labels that each got.

#45 feat: add inventory screen titles
  assets/skins/inventoryDefault.skin
  assets/ui/ingame/containerScreen.ui
  assets/ui/ingame/inventoryScreen.ui
  src/main/java/org/terasology/module/inventory/ui/ContainerScreen.java
Labels: Type: Improvement, Category: Gameplay Content, Topic: UI/UX

#46 fix: retrieve character entity within binding
  src/main/java/org/terasology/module/inventory/ui/ContainerScreen.java
Labels: Type: Bug, Multiplayer

#47 fix: avoid NPE in binding for container title
  src/main/java/org/terasology/module/inventory/ui/ContainerScreen.java
Labels: Type: Bug, Topic: UI/UX
